### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xhyrom** [xHyroM/lighteco#1]
- [ ] Cache
   - Redis
- [ ] Messaging
   - Plugin messaging
   - [x] Redis messaging
- [x] Github Actions CI
- [x] PlaceholderAPI for Bukkit
- [x] Remove `bukkittest` module
- [x] Create `test` module with different platforms to test them
- [x] Better command abstraction (https://github.com/xHyroM/lighteco/pull/4)
- [ ] Bank 🏦 support

## Platforms

- [ ] Bukkit
- [x] Paper (currently supported using [Bukkit](https://github.com/xHyroM/lighteco/tree/main/bukkit) platform)
   - technically supported, but we want to use `paper-plugin.yml` instead `plugin.yml` for paper loader
- [ ] Sponge 7
- [ ] Sponge 8
- [ ] Sponge 9
- [ ] Forge
- [ ] Fabric
- [ ] Nukkit
- [ ] Minestom

## Money currency module

- [x] Configuration
- [x] Vault hook (for bukkit)

This plugin is WIP. There can be issues. First stable release will be on Modrinth
